version: "3.9"

services:
  vault:
    container_name: vault
    cap_add:
      - IPC_LOCK
    image: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
  config:
    container_name: eth-config-server
    image: docker.io/westbrook/eth-config-server:latest
    ports:
      - "8888:8888"
    environment:
      VAULT_TOKEN: vault
      VAULT_HOST: vault:8200